### ISSUE TITLE
Exception in thread "main" java.lang.RuntimeException

### ISSUE THREAD

**Issue by Malichot** [muelletm/cistern#12]
Dear all,

I'm encountering a problem while trying to use a trained model.  I use this version of Java : 

> java version "1.8.0_201"
> Java(TM) SE Runtime Environment (build 1.8.0_201-b09)
> Java HotSpot(TM) 64-Bit Server VM (build 25.201-b09, mixed mode)

And I got this error :

> Exception in thread "main" java.lang.RuntimeException: java.io.InvalidClassException: marmot.morph.MorphModel; local class incompatible: stream classdesc serialVersionUID = 2, local class serialVersionUID = 1
	at marmot.core.SimpleTagger.loadFromFile(SimpleTagger.java:688)
	at marmot.morph.cmd.Annotator.main(Annotator.java:41)
Caused by: java.io.InvalidClassException: marmot.morph.MorphModel; local class incompatible: stream classdesc serialVersionUID = 2, local class serialVersionUID = 1
	at java.io.ObjectStreamClass.initNonProxy(ObjectStreamClass.java:699)
	at java.io.ObjectInputStream.readNonProxyDesc(ObjectInputStream.java:1885)
	at java.io.ObjectInputStream.readClassDesc(ObjectInputStream.java:1751)
	at java.io.ObjectInputStream.readOrdinaryObject(ObjectInputStream.java:2042)
	at java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1573)
	at java.io.ObjectInputStream.defaultReadFields(ObjectInputStream.java:2287)
	at java.io.ObjectInputStream.readSerialData(ObjectInputStream.java:2167)
	at java.io.ObjectInputStream.readOrdinaryObject(ObjectInputStream.java:2069)
	at java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1573)
	at java.io.ObjectInputStream.readObject(ObjectInputStream.java:431)
	at marmot.core.SimpleTagger.loadFromFile(SimpleTagger.java:670)
	... 1 more

My test file is structured following your indications in a one-word-per-line format. Do you know what the problem is ? 

Thanks in advance :)

**Comment by Malichot** [comment]
Dear all,

Problem solved by using the "marmot-2015-10-22.jar" version instead of the "marmot.jar".

Best regards
