### ISSUE TITLE
MarMoT compiled, but is throwing errors

### ISSUE THREAD

**Issue by pmarcis** [muelletm/cistern#4]
Hi,

I cloned the solution from GitHub:
```
git clone https://github.com/muelletm/cistern.git
```
 compiled it with ant on Linux:
```
ant
```
The result of compilation was:
```
Buildfile: /tmp/marcis/cistern/marmot/build.xml

clean:

timestamp:
     [echo] TIME: 10/01/2015 02:04:19 PM

compile:
    [mkdir] Created dir: /tmp/marcis/cistern/marmot/classes
    [javac] Compiling 300 source files to /tmp/marcis/cistern/marmot/classes
    [javac] warning: [options] bootstrap class path not set in conjunction with -source 1.7
    [javac] 1 warning

jar:
      [jar] Building jar: /tmp/marcis/cistern/marmot/marmot-2015-10-01.jar

BUILD SUCCESSFUL
```
Then I downloaded the English model file:
```
wget http://cistern.cis.lmu.de/marmot/models/mte/en.marmot
```
Then I created a test file containing just one sentence (en_text.txt):
```
This
is
a
test
.
```
Then I executed MarMoT:
```
java -cp marmot-2015-10-01.jar marmot.morph.cmd.Annotator --model-file en.marmot --test-file form-index=0,en_text.txt --pred-file en_text.out.txt
```
It crashed:
```
Exception in thread "main" java.lang.ClassCastException: cannot assign instance of marmot.util.SymbolTable to field marmot.morph.MorphWeightVector.feature_table_ of type marmot.util.FeatureTable in instance of marmot.morph.MorphWeightVector
        at java.io.ObjectStreamClass$FieldReflector.setObjFieldValues(ObjectStreamClass.java:2089)
        at java.io.ObjectStreamClass.setObjFieldValues(ObjectStreamClass.java:1261)
        at java.io.ObjectInputStream.defaultReadFields(ObjectInputStream.java:2006)
        at java.io.ObjectInputStream.readSerialData(ObjectInputStream.java:1924)
        at java.io.ObjectInputStream.readOrdinaryObject(ObjectInputStream.java:1801)
        at java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1351)
        at java.io.ObjectInputStream.defaultReadFields(ObjectInputStream.java:2000)
        at java.io.ObjectInputStream.readSerialData(ObjectInputStream.java:1924)
        at java.io.ObjectInputStream.readOrdinaryObject(ObjectInputStream.java:1801)
        at java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1351)
        at java.io.ObjectInputStream.readObject(ObjectInputStream.java:371)
        at marmot.util.FileUtils.loadFromFile(FileUtils.java:75)
        at marmot.util.FileUtils.loadFromFile(FileUtils.java:66)
        at marmot.morph.cmd.Annotator.main(Annotator.java:40)
```
Is it possible that the pre-trained models are no more compattible with the current code base?

**Comment by pdonald** [comment]
Try using the latest release:

```
$ wget http://cistern.cis.lmu.de/marmot/bin/CURRENT/marmot-2015-10-22.jar
$ wget http://cistern.cis.lmu.de/marmot/models/CURRENT/mte/en.marmot
$ echo -e "Hello\nworld\n!" | java -cp marmot-2015-10-22.jar marmot.morph.cmd.Annotator --model-file en.marmot --test-file form-index=0,/dev/stdin --pred-file /dev/stdout
1       Hello   _       _       _       D       _       D0D|D_D|D|D1g|D_g|g
2       world   _       _       _       N       _       N0N|N_N|N|N1c|N_c|c|N2n|N_n|n|N3s|N_s|s
3       !       _       _       _       c       _       c0c|c_c|c
```

**Comment by pmarcis** [comment]
Thanks for the update!
